"""plot_energy_drift.py
Reads CSVs emitted by bench_energy_drift.exe and produces PNG figures plus
matching <name>_desc.md per CLAUDE.md visualization standards.

Usage:
    python scripts/plot_energy_drift.py              # default outputs/figures/
    python scripts/plot_energy_drift.py <dir>
"""
from __future__ import annotations

import csv
import sys
from datetime import date
from pathlib import Path

import matplotlib
matplotlib.use("Agg")  # no display
import matplotlib.pyplot as plt


# ----------------------------------------------------------------------------
def _read_csv(path: Path) -> tuple[list[str], list[list[float]]]:
    with path.open(newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr)
        cols: list[list[float]] = [[] for _ in header]
        for row in rdr:
            for i, v in enumerate(row):
                cols[i].append(float(v))
    return header, cols


def _xticks(t: list[float]) -> list[float]:
    if not t:
        return []
    n = 5
    step = (t[-1] - t[0]) / (n - 1) if n > 1 else 0
    return [t[0] + i * step for i in range(n)]


def _save(fig: plt.Figure, png_path: Path) -> None:
    fig.savefig(png_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[plot] wrote {png_path}")


def _write_desc(name: str, csv_path: Path,
                observations: list[str], axes: list[str]) -> None:
    desc = csv_path.parent / f"{name}_desc.md"
    body = (
        f"# Figure: {name}\n\n"
        "## Purpose\n"
        "Quantitative drift of conserved quantities in the Basements integrator.\n\n"
        "## Data Source\n"
        f"- File: {csv_path.name}\n"
        "- Generated by: bench_energy_drift.exe + scripts/plot_energy_drift.py\n"
        f"- Date: {date.today().isoformat()}\n\n"
        "## Axes\n"
        + "\n".join(f"- {a}" for a in axes) + "\n\n"
        "## Key Observations\n"
        + "\n".join(f"- {o}" for o in observations) + "\n\n"
        "## Reproduction\n"
        "```\n"
        "cmake --build build --config Release --target bench_energy_drift\n"
        "./build/Release/bench_energy_drift.exe\n"
        "python scripts/plot_energy_drift.py\n"
        "```\n"
    )
    desc.write_text(body, encoding="utf-8")
    print(f"[plot] wrote {desc}")


# ----------------------------------------------------------------------------
def plot_free_fall(csv_path: Path) -> None:
    header, cols = _read_csv(csv_path)
    t, KE, PE, E_total = cols[0], cols[1], cols[2], cols[3]

    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.plot(t, KE,      label="Kinetic Energy")
    ax.plot(t, PE,      label="Potential Energy")
    ax.plot(t, E_total, label="Total Energy", linewidth=2)
    ax.set_xlabel("time (s)")
    ax.set_ylabel("energy (J)")
    ax.set_title("Free Fall — Energy Components")
    ax.set_xticks(_xticks(t))
    ax.grid(alpha=0.3)
    ax.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    name = "energy_free_fall"
    _save(fig, csv_path.parent / f"{name}.png")

    drift_pct = abs(E_total[-1] - E_total[0]) / abs(E_total[0]) * 100
    _write_desc(
        name, csv_path,
        observations=[
            f"E_total(0) = {E_total[0]:.6f} J",
            f"E_total(T) = {E_total[-1]:.6f} J",
            f"|drift| = {drift_pct:.4f} %  (target: <1%)",
        ],
        axes=[
            f"X: time (s) — range: {t[0]:.3f} to {t[-1]:.3f}, dt sample 1/240",
            "Y: energy (J)",
        ],
    )


def plot_momentum(csv_path: Path) -> None:
    header, cols = _read_csv(csv_path)
    t = cols[0]
    px, py, pz = cols[1], cols[2], cols[3]
    Lx, Ly, Lz = cols[4], cols[5], cols[6]
    KE = cols[7]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 6.5), sharex=True)
    ax1.plot(t, px, label="p_x")
    ax1.plot(t, py, label="p_y")
    ax1.plot(t, pz, label="p_z")
    ax1.set_ylabel("linear momentum (kg·m/s)")
    ax1.set_title("Isolated 2-Body — Conservation Check")
    ax1.grid(alpha=0.3)
    ax1.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    ax2.plot(t, Lx, label="L_x")
    ax2.plot(t, Ly, label="L_y")
    ax2.plot(t, Lz, label="L_z")
    ax2.set_xlabel("time (s)")
    ax2.set_ylabel("angular momentum (kg·m²/s)")
    ax2.set_xticks(_xticks(t))
    ax2.grid(alpha=0.3)
    ax2.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    name = "momentum_isolated_pair"
    _save(fig, csv_path.parent / f"{name}.png")

    def drift(a: list[float]) -> float:
        return abs(a[-1] - a[0])

    _write_desc(
        name, csv_path,
        observations=[
            f"|Δp_x|, |Δp_y|, |Δp_z| = "
            f"{drift(px):.3e}, {drift(py):.3e}, {drift(pz):.3e}",
            f"|ΔL_x|, |ΔL_y|, |ΔL_z| = "
            f"{drift(Lx):.3e}, {drift(Ly):.3e}, {drift(Lz):.3e}",
            f"KE_sys(0) → KE_sys(T) = {KE[0]:.6f} → {KE[-1]:.6f} J",
            "Targets: |Δp| < 1e-5, |ΔL| < 1e-4 (float32 roundoff).",
        ],
        axes=[
            f"X: time (s) — range: {t[0]:.3f} to {t[-1]:.3f}",
            "Y (top): linear momentum (kg·m/s)",
            "Y (bot): angular momentum about origin (kg·m²/s)",
        ],
    )


def plot_damped(csv_path: Path) -> None:
    header, cols = _read_csv(csv_path)
    t, KE, vx = cols[0], cols[1], cols[2]

    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.plot(t, KE, label="Kinetic Energy")
    ax.set_xlabel("time (s)")
    ax.set_ylabel("KE (J)")
    ax.set_title("Damped Slider — Monotone Energy Dissipation")
    ax.set_xticks(_xticks(t))
    ax.grid(alpha=0.3)
    ax.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    name = "energy_damped_slider"
    _save(fig, csv_path.parent / f"{name}.png")

    monotone = all(KE[i + 1] <= KE[i] + 1e-9 for i in range(len(KE) - 1))
    _write_desc(
        name, csv_path,
        observations=[
            f"KE(0) = {KE[0]:.6f} J, KE(T) = {KE[-1]:.6f} J",
            f"Monotone non-increasing: {monotone}",
            f"Final vx = {vx[-1]:.6f} m/s",
        ],
        axes=[
            f"X: time (s) — range: {t[0]:.3f} to {t[-1]:.3f}",
            "Y: kinetic energy (J)",
        ],
    )


def plot_solver_stack(csv_path: Path) -> None:
    header, cols = _read_csv(csv_path)
    t = cols[0]
    y1, y2, y3 = cols[1], cols[2], cols[3]
    d1, d2, d3 = cols[4], cols[5], cols[6]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 6.5), sharex=True)
    ax1.plot(t, y1, label="y_bottom (target 0.50)")
    ax1.plot(t, y2, label="y_middle (target 1.50)")
    ax1.plot(t, y3, label="y_top    (target 2.50)")
    ax1.set_ylabel("height (m)")
    ax1.set_title("Box-Stack Drift — PhysicsWorldGPU (Sequential Impulse + Warm Start)")
    ax1.grid(alpha=0.3)
    ax1.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    ax2.plot(t, d1, label="bottom")
    ax2.plot(t, d2, label="middle")
    ax2.plot(t, d3, label="top")
    ax2.axhline(0.0, color="k", linewidth=0.5)
    ax2.set_xlabel("time (s)")
    ax2.set_ylabel("drift from initial (m)")
    ax2.set_xticks(_xticks(t))
    ax2.grid(alpha=0.3)
    ax2.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    name = "solver_stack_drift"
    _save(fig, csv_path.parent / f"{name}.png")
    _write_desc(
        name, csv_path,
        observations=[
            f"final drift (m): bottom={d1[-1]:.4f}, middle={d2[-1]:.4f}, top={d3[-1]:.4f}",
            f"max |drift| (m): {max(abs(min(d1)), abs(max(d1))):.4f} / "
            f"{max(abs(min(d2)), abs(max(d2))):.4f} / "
            f"{max(abs(min(d3)), abs(max(d3))):.4f}",
            "Target: |drift| < 0.05 m sustained (within solver tolerance band).",
        ],
        axes=[
            f"X: time (s) — range: {t[0]:.3f} to {t[-1]:.3f}, dt=1/240",
            "Y (top): absolute height (m)",
            "Y (bot): drift relative to settled initial pose (m)",
        ],
    )


def plot_solver_pendulum(csv_path: Path) -> None:
    header, cols = _read_csv(csv_path)
    t        = cols[0]
    angle    = cols[1]
    KE       = cols[2]
    PE       = cols[3]
    E_total  = cols[4]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 6.5), sharex=True)
    ax1.plot(t, angle, label="pendulum angle")
    ax1.set_ylabel("angle (deg)")
    ax1.set_title("Hinge Pendulum — PhysicsWorldGPU Joint Solver")
    ax1.grid(alpha=0.3)
    ax1.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    ax2.plot(t, KE,      label="KE")
    ax2.plot(t, PE,      label="PE")
    ax2.plot(t, E_total, label="Total", linewidth=2)
    ax2.set_xlabel("time (s)")
    ax2.set_ylabel("energy (J)")
    ax2.set_xticks(_xticks(t))
    ax2.grid(alpha=0.3)
    ax2.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    name = "solver_pendulum"
    _save(fig, csv_path.parent / f"{name}.png")

    e_drift = (E_total[-1] - E_total[0])
    _write_desc(
        name, csv_path,
        observations=[
            f"E_total(0) = {E_total[0]:.4f} J, E_total(T) = {E_total[-1]:.4f} J",
            f"ΔE over {t[-1]:.1f} s = {e_drift:+.4f} J "
            f"({(e_drift / max(abs(E_total[0]), 1e-9) * 100):+.2f} %)",
            "Real pendulums in this solver lose energy slowly via Baumgarte; "
            "monotone non-increasing total energy is the expected signature.",
        ],
        axes=[
            f"X: time (s) — range: {t[0]:.3f} to {t[-1]:.3f}",
            "Y (top): angle (deg) — initial release at 0° (horizontal)",
            "Y (bot): kinetic / potential / total energy (J)",
        ],
    )


def plot_mpm_rigid(csv_path: Path) -> None:
    header, cols = _read_csv(csv_path)
    t       = cols[0]
    box_y   = cols[1]
    box_vy  = cols[2]
    p_body  = cols[3]
    p_grid  = cols[4]
    p_sum   = cols[5]
    KE      = cols[6]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 7), sharex=True)
    ax1.plot(t, box_y,  label="box height (m)")
    ax1.plot(t, box_vy, label="box v_y (m/s)")
    ax1.set_ylabel("kinematics")
    ax1.set_title("MPM ↔ Rigid Coupling MVP — Reference Baseline (M0)")
    ax1.grid(alpha=0.3)
    ax1.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    ax2.plot(t, p_body, label="Σ body p_y")
    ax2.plot(t, p_grid, label="Σ grid p_y")
    ax2.plot(t, p_sum,  label="total p_y (conservation error)", linewidth=2)
    ax2.axhline(0.0, color="k", linewidth=0.5)
    ax2.set_xlabel("time (s)")
    ax2.set_ylabel("momentum (kg·m/s)")
    ax2.set_xticks(_xticks(t))
    ax2.grid(alpha=0.3)
    ax2.legend(bbox_to_anchor=(1.01, 1), loc="upper left")

    name = csv_path.stem      # use CSV basename so dirichlet + pic don't collide
    method = "PIC-Rigid (M1)" if name.endswith("_pic") else "Dirichlet (M0 MVP)"
    ax1.set_title(f"MPM ↔ Rigid Coupling — {method} (Baseline)")
    _save(fig, csv_path.parent / f"{name}.png")

    max_err = max(abs(v) for v in p_sum)
    _write_desc(
        name, csv_path,
        observations=[
            f"Method   = {method}",
            f"Final box height = {box_y[-1]:.4f} m, v_y = {box_vy[-1]:.4f} m/s",
            f"max |Σ p_y| = {max_err:.4e} kg·m/s",
            "Target for M1 PIC: 10× smaller than M0 Dirichlet on the same axis.",
            "Target for M2 ASFLIP: float-roundoff bounded |Σ p_y|.",
        ],
        axes=[
            f"X: time (s) — range: {t[0]:.3f} to {t[-1]:.3f}, dt=1/240",
            "Y (top): box height (m) and v_y (m/s)",
            "Y (bot): linear momentum (kg·m/s) — body / grid / sum",
        ],
    )


# ----------------------------------------------------------------------------
PLOTTERS = {
    "energy_free_fall.csv":         plot_free_fall,
    "momentum_isolated_pair.csv":   plot_momentum,
    "energy_damped_slider.csv":     plot_damped,
    "solver_stack_drift.csv":       plot_solver_stack,
    "solver_pendulum.csv":          plot_solver_pendulum,
    "mpm_rigid_drift.csv":          plot_mpm_rigid,
    # M1 PIC-Rigid CSV uses the same column layout, so it reuses plot_mpm_rigid.
    "mpm_rigid_drift_pic.csv":      plot_mpm_rigid,
}


def main(argv: list[str]) -> int:
    out_dir = Path(argv[1]) if len(argv) > 1 else Path("outputs/figures")
    if not out_dir.is_dir():
        print(f"[plot] directory not found: {out_dir}", file=sys.stderr)
        return 1
    any_done = False
    for name, fn in PLOTTERS.items():
        path = out_dir / name
        if path.exists():
            fn(path)
            any_done = True
        else:
            print(f"[plot] skipped (missing): {path}")
    if not any_done:
        print("[plot] no CSVs found — run bench_energy_drift first.")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
